runtime: php81 # Adjust to your PHP version
instance_class: F1 # Choose an instance class

env_variables:
  APP_ENV: "production"
  APP_KEY: "your-app-key"

handlers:
- url: /(.*)
  script: auto

# Automatic scaling settings
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
