apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: xampp-cloud
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/YOUR_PROJECT_ID/xampp-image:latest
          ports:
            - containerPort: 80
